### ISSUE TITLE
crossing=marked deprecato?

### ISSUE THREAD

**Issue by dalz** [fansanelli/map-this-way#3]
Sarebbe possibile avere una fonte per questo check? Nella wiki [1] non è scritto, e anzi dice che è il tag usato dal preset di iD, e c'è una proposta [2] che lo utilizza per risolvere le ambiguità delle altre modalità di tagging.

[1] https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcrossing
[2] https://wiki.openstreetmap.org/wiki/Proposed_features/crossing%3Dmarked

**Comment by fansanelli** [comment]
ciao,

essendo un duplicato di uncontrolled non ha senso usarlo per quanto mi riguarda.

Francesco

**Comment by dalz** [comment]
Capisco, penso che continuerò ad usare crossing=marked allora visto che è quello più diffuso e semanticamente corretto. Grazie!

**Comment by fansanelli** [comment]
Essendo che non è mai stato deprecato, ho modificato il messaggio.
Ho aggiunto il suggerimento di usare piuttosto "uncontrolled" insieme a "crossing:markings" che mi sembra sia la cosa più corretta secondo le ultime modifiche della wiki.
